version: '2'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=repender
      - POSTGRES_PASSWORD=r3p3nd
      - POSTGRES_DB=repend
      - PGDATA=/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/pgdata
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  repend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - node_modules:/server/node_modules

  sut:
    build: .
    ports:
      - "3001:3000"
    entrypoint: npm run test:watch
    volumes:
      - ./server:/server
      - node_modules:/server/node_modules

volumes:
  pgdata:
  node_modules: