version: '2'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pender
      - POSTGRES_PASSWORD=p3nd
      - POSTGRES_DB=pend
      - PGDATA=/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/pgdata
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  repend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - /server/node_modules

volumes:
  pgdata: